import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import compression from 'compression';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import crypto from 'node:crypto';
import Razorpay from 'razorpay';
import { createClient } from '@supabase/supabase-js';

const app=express();
const PORT=Number(process.env.PORT||8080);
const APP_URL=process.env.APP_URL||`http://localhost:${PORT}`;
const required=['SUPABASE_URL','SUPABASE_PUBLISHABLE_KEY','SUPABASE_SERVICE_ROLE_KEY','RAZORPAY_KEY_ID','RAZORPAY_KEY_SECRET','RAZORPAY_WEBHOOK_SECRET'];
const missing=required.filter(k=>!process.env[k]);
if(missing.length) console.warn(`Missing environment variables: ${missing.join(', ')}`);
const supabaseAdmin=createClient(process.env.SUPABASE_URL||'https://placeholder.invalid',process.env.SUPABASE_SERVICE_ROLE_KEY||'service-role-placeholder',{auth:{autoRefreshToken:false,persistSession:false}});
const supabasePublic=createClient(process.env.SUPABASE_URL||'https://placeholder.invalid',process.env.SUPABASE_PUBLISHABLE_KEY||'public-placeholder');
const razorpay=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID||'placeholder',key_secret:process.env.RAZORPAY_KEY_SECRET||'placeholder'});
app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'},contentSecurityPolicy:false}));
app.use(compression());
const allowedOrigins=(process.env.ALLOWED_ORIGINS||APP_URL).split(',').map(x=>x.trim()).filter(Boolean);
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.includes('*')||allowedOrigins.includes(origin))return cb(null,true);return cb(new Error('CORS blocked'))},credentials:false}));
const apiLimiter=rateLimit({windowMs:60000,max:150,standardHeaders:true,legacyHeaders:false});
const publicEventLimiter=rateLimit({windowMs:60000,max:60,standardHeaders:true,legacyHeaders:false});
const authLimiter=rateLimit({windowMs:60000,max:30,standardHeaders:true,legacyHeaders:false});
const paymentLimiter=rateLimit({windowMs:60000,max:15,standardHeaders:true,legacyHeaders:false});
const aiLimiter=rateLimit({windowMs:60000,max:25,standardHeaders:true,legacyHeaders:false});
app.use('/api/',apiLimiter);
function timingSafe(a,b){const A=Buffer.from(String(a));const B=Buffer.from(String(b));return A.length===B.length&&crypto.timingSafeEqual(A,B)}
function bearer(req){const h=req.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7):null}
async function userFromToken(token){if(!token)return null;const {data,error}=await supabasePublic.auth.getUser(token);return error?null:data?.user||null}
async function requireUser(req,res,next){try{const u=await userFromToken(bearer(req));if(!u)return res.status(401).json({error:'Authentication required'});req.user=u;next()}catch{return res.status(401).json({error:'Authentication failed'})}}
async function profileFor(userId){const {data}=await supabaseAdmin.from('profiles').select('*').eq('id',userId).maybeSingle();return data}
function adminAllowed(user){if(!user)return false;const emails=(process.env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return emails.includes(String(user.email||'').toLowerCase())}
async function requireAdmin(req,res,next){try{const u=await userFromToken(bearer(req));if(!u)return res.status(401).json({error:'Authentication required'});const p=await profileFor(u.id);if(p?.role!=='admin'&&!adminAllowed(u))return res.status(403).json({error:'Admin access required'});req.user=u;req.profile=p;next()}catch(e){res.status(401).json({error:'Admin authentication failed'})}}
async function ownedBusiness(userId){const {data,error}=await supabaseAdmin.from('businesses').select('*').eq('owner_id',userId).maybeSingle();if(error)throw error;return data}
function planId(plan){return plan==='pro'?process.env.RAZORPAY_PRO_PLAN_ID:plan==='elite'?process.env.RAZORPAY_ELITE_PLAN_ID:null}
function activePaid(b){return !!b&&['pro','elite'].includes(b.plan)&&b.subscription_status==='active'&&(!b.subscription_current_end||new Date(b.subscription_current_end)>new Date())}
function slugify(name){return (name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+crypto.randomBytes(3).toString('hex')).slice(0,70)}
function publicSupabaseKey(){
	const key=process.env.SUPABASE_PUBLISHABLE_KEY||'';
	if(!key||key===process.env.SUPABASE_SERVICE_ROLE_KEY||/^sb_secret_/i.test(key))return '';
	const payload=key.split('.')[1];
	if(payload){try{if(JSON.parse(Buffer.from(payload,'base64url').toString('utf8')).role==='service_role')return ''}catch{}}
	return key;
}

// Razorpay webhook must see raw bytes.
app.post('/api/payments/webhook',express.raw({type:'application/json'}),async(req,res)=>{try{const sig=req.get('x-razorpay-signature')||'';const expected=crypto.createHmac('sha256',process.env.RAZORPAY_WEBHOOK_SECRET||'').update(req.body).digest('hex');if(!timingSafe(sig,expected))return res.status(400).json({error:'Invalid webhook signature'});const event=JSON.parse(req.body.toString('utf8'));const sub=event?.payload?.subscription?.entity;const payment=event?.payload?.payment?.entity;await supabaseAdmin.from('payment_events').insert({event_name:event.event,razorpay_id:sub?.id||payment?.id||null,payload:event});const sid=sub?.id||payment?.subscription_id;if(sid){const patch={updated_at:new Date().toISOString()};if(sub){patch.subscription_status=['active','authenticated'].includes(sub.status)?'active':sub.status;patch.subscription_current_end=sub.current_end?new Date(sub.current_end*1000).toISOString():null;if(['cancelled','completed','expired'].includes(sub.status))patch.plan='free'}await supabaseAdmin.from('businesses').update(patch).eq('subscription_id',sid)}return res.json({ok:true})}catch(e){console.error(e);return res.status(400).json({error:'Webhook processing failed'})}});
app.use(express.json({limit:'2mb'}));
app.use(express.static('public',{extensions:['html']}));

app.get('/api/health',(_req,res)=>res.json({ok:true,service:'imphal-connect',version:'2.1.0',time:new Date().toISOString()}));
app.get('/api/config',(_req,res)=>res.json({supabase:{url:process.env.SUPABASE_URL||'',key:publicSupabaseKey()}}));

app.get('/api/me',requireUser,async(req,res)=>{const profile=await profileFor(req.user.id);const business=await ownedBusiness(req.user.id);res.json({user:{id:req.user.id,email:req.user.email},profile,business})});
app.post('/api/business',authLimiter,requireUser,async(req,res)=>{const existing=await ownedBusiness(req.user.id);if(existing)return res.status(409).json({error:'Business already exists',business:existing});const name=String(req.body.name||'').trim();if(name.length<2||name.length>120)return res.status(400).json({error:'Business name must be 2-120 characters'});const payload={owner_id:req.user.id,name,slug:slugify(name),category:String(req.body.category||'Services').slice(0,60),description:String(req.body.description||'').slice(0,4000),phone:String(req.body.phone||'').slice(0,40),whatsapp:String(req.body.whatsapp||'').slice(0,40),address:String(req.body.address||'').slice(0,300),is_published:false};const {data,error}=await supabaseAdmin.from('businesses').insert(payload).select('*').single();if(error)return res.status(400).json({error:error.message});res.status(201).json({business:data})});
app.patch('/api/business',requireUser,async(req,res)=>{const allowed=['name','category','description','phone','whatsapp','address','city','latitude','longitude','logo_url','cover_url','is_published'];const patch=Object.fromEntries(Object.entries(req.body||{}).filter(([k])=>allowed.includes(k)));patch.updated_at=new Date().toISOString();const {data,error}=await supabaseAdmin.from('businesses').update(patch).eq('owner_id',req.user.id).select('*').single();if(error)return res.status(400).json({error:error.message});res.json({business:data})});
app.get('/api/businesses',async(req,res)=>{const q=String(req.query.q||'').trim();const category=String(req.query.category||'').trim();let query=supabaseAdmin.from('businesses').select('id,name,slug,category,description,phone,whatsapp,address,city,logo_url,cover_url,is_verified,plan').eq('is_published',true).limit(100);if(category)query=query.eq('category',category);if(q){const safeQ=q.replace(/[\\,(){}\[\]]/g,' ').replace(/\s+/g,' ').trim().slice(0,80);if(safeQ)query=query.or(`name.ilike.%${safeQ}%,description.ilike.%${safeQ}%,category.ilike.%${safeQ}%`)}const {data,error}=await query.order('is_verified',{ascending:false}).order('name');if(error)return res.status(500).json({error:error.message});res.json({businesses:data||[]})});
app.get('/api/businesses/:slug',async(req,res)=>{const {data,error}=await supabaseAdmin.from('businesses').select('*').eq('slug',req.params.slug).eq('is_published',true).maybeSingle();if(error||!data)return res.status(404).json({error:'Business not found'});const [items,stories,offers]=await Promise.all([supabaseAdmin.from('business_items').select('*').eq('business_id',data.id).eq('is_active',true).order('created_at',{ascending:false}),supabaseAdmin.from('business_stories').select('*').eq('business_id',data.id).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}),supabaseAdmin.from('business_offers').select('*').eq('business_id',data.id).eq('is_active',true).or(`expires_at.is.null,expires_at.gt.${new Date().toISOString()}`).order('created_at',{ascending:false})]);res.json({business:data,items:items.data||[],stories:stories.data||[],offers:offers.data||[]})});

app.post('/api/items',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!activePaid(b))return res.status(403).json({error:'An active Pro or Elite subscription is required'});const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({error:'Item/service name required'});const raw=req.body.price;const price=raw===null||raw===undefined||raw===''?null:Number(raw);if(price!==null&&(!Number.isFinite(price)||price<0))return res.status(400).json({error:'Invalid price'});const {data,error}=await supabaseAdmin.from('business_items').insert({business_id:b.id,name:name.slice(0,160),price,description:String(req.body.description||'').slice(0,1000),image_url:String(req.body.image_url||'').slice(0,1000)}).select('*').single();if(error)return res.status(400).json({error:error.message});res.status(201).json({item:data})});
app.patch('/api/items/:id',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!activePaid(b))return res.status(403).json({error:'Active Pro/Elite required'});const patch=Object.fromEntries(Object.entries(req.body||{}).filter(([k])=>['name','price','description','image_url','is_active'].includes(k)));patch.updated_at=new Date().toISOString();const {data,error}=await supabaseAdmin.from('business_items').update(patch).eq('id',req.params.id).eq('business_id',b.id).select('*').single();if(error)return res.status(400).json({error:error.message});res.json({item:data})});
app.delete('/api/items/:id',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);const {error}=await supabaseAdmin.from('business_items').delete().eq('id',req.params.id).eq('business_id',b?.id);if(error)return res.status(400).json({error:error.message});res.json({ok:true})});
app.post('/api/stories',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!activePaid(b))return res.status(403).json({error:'An active Pro or Elite subscription is required'});const {data,error}=await supabaseAdmin.from('business_stories').insert({business_id:b.id,title:String(req.body.title||'').slice(0,120),image_url:String(req.body.image_url||'').slice(0,1000),expires_at:new Date(Date.now()+86400000).toISOString()}).select('*').single();if(error)return res.status(400).json({error:error.message});res.status(201).json({story:data})});
app.post('/api/offers',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!activePaid(b))return res.status(403).json({error:'Active Pro/Elite required'});const title=String(req.body.title||'').trim();if(!title)return res.status(400).json({error:'Offer title required'});const {data,error}=await supabaseAdmin.from('business_offers').insert({business_id:b.id,title:title.slice(0,160),description:String(req.body.description||'').slice(0,1000),discount_text:String(req.body.discount_text||'').slice(0,80),expires_at:req.body.expires_at||null}).select('*').single();if(error)return res.status(400).json({error:error.message});res.status(201).json({offer:data})});

app.post('/api/billing/create-subscription',paymentLimiter,requireUser,async(req,res)=>{const plan=String(req.body.plan||'').toLowerCase();if(!['pro','elite'].includes(plan))return res.status(400).json({error:'Choose Pro or Elite'});const id=planId(plan);if(!id)return res.status(503).json({error:`Razorpay ${plan} plan ID is not configured`});const b=await ownedBusiness(req.user.id);if(!b)return res.status(400).json({error:'Create your business before subscribing'});try{const sub=await razorpay.subscriptions.create({plan_id:id,total_count:Number(process.env.RAZORPAY_TOTAL_COUNT||120),customer_notify:1,notes:{business_id:b.id,user_id:req.user.id,plan}});await supabaseAdmin.from('businesses').update({subscription_id:sub.id,plan,subscription_status:sub.status||'created',updated_at:new Date().toISOString()}).eq('id',b.id);res.json({subscriptionId:sub.id,keyId:process.env.RAZORPAY_KEY_ID,plan,subscription:sub})}catch(e){res.status(502).json({error:e?.error?.description||e.message||'Could not create subscription'})}});
app.post('/api/billing/verify-subscription',paymentLimiter,requireUser,async(req,res)=>{const {razorpay_payment_id,razorpay_subscription_id,razorpay_signature}=req.body||{};if(!razorpay_payment_id||!razorpay_subscription_id||!razorpay_signature)return res.status(400).json({error:'Missing Razorpay verification fields'});const b=await ownedBusiness(req.user.id);if(!b||b.subscription_id!==razorpay_subscription_id)return res.status(403).json({error:'Subscription does not belong to this business'});const generated=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET||'').update(`${razorpay_payment_id}|${razorpay_subscription_id}`).digest('hex');if(!timingSafe(generated,razorpay_signature))return res.status(400).json({error:'Invalid Razorpay signature'});try{const sub=await razorpay.subscriptions.fetch(razorpay_subscription_id);const status=['active','authenticated'].includes(sub.status)?'active':sub.status;await supabaseAdmin.from('businesses').update({subscription_status:status,subscription_current_end:sub.current_end?new Date(sub.current_end*1000).toISOString():null,updated_at:new Date().toISOString()}).eq('id',b.id);res.json({ok:true,status})}catch(e){res.status(502).json({error:'Payment verified but subscription status is pending webhook confirmation'})}});
app.post('/api/billing/cancel',paymentLimiter,requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!b?.subscription_id)return res.status(400).json({error:'No subscription found'});try{const sub=await razorpay.subscriptions.cancel(b.subscription_id,{cancel_at_cycle_end:1});await supabaseAdmin.from('businesses').update({subscription_status:sub.status||b.subscription_status,updated_at:new Date().toISOString()}).eq('id',b.id);res.json({ok:true,subscription:sub})}catch(e){res.status(502).json({error:e?.error?.description||e.message||'Cancellation failed'})}});

app.post('/api/upload/sign',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!b)return res.status(400).json({error:'Create a business first'});if(!activePaid(b))return res.status(403).json({error:'An active Pro or Elite subscription is required'});const ext=String(req.body.extension||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,5)||'jpg';const allowedExt=['jpg','jpeg','png','webp'];if(!allowedExt.includes(ext))return res.status(400).json({error:'Only JPG, PNG and WebP images are supported'});const path=`${req.user.id}/${crypto.randomUUID()}.${ext}`;const {data,error}=await supabaseAdmin.storage.from('business-media').createSignedUploadUrl(path);if(error)return res.status(400).json({error:error.message});res.json({path,token:data.token,publicBase:`${process.env.SUPABASE_URL}/storage/v1/object/public/business-media/${path}`})});

app.post('/api/leads',publicEventLimiter,async(req,res)=>{
    const businessId=String(req.body.business_id||'').trim();
    const customerName=String(req.body.customer_name||'').trim().slice(0,120);
    const customerPhone=String(req.body.customer_phone||'').trim().slice(0,40);
    const customerEmail=String(req.body.customer_email||'').trim().slice(0,160);
    const message=String(req.body.message||'').trim().slice(0,2000);
    if(!businessId||customerName.length<2||message.length<2)return res.status(400).json({error:'Name, business and message are required'});
    const {data:business,error:be}=await supabaseAdmin.from('businesses').select('id,name,is_published').eq('id',businessId).eq('is_published',true).maybeSingle();
    if(be||!business)return res.status(404).json({error:'Business not found'});
    let customerId=null;
    const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();
    if(token){try{const {data}=await supabaseAdmin.auth.getUser(token);customerId=data?.user?.id||null}catch{}}
    const {data,error}=await supabaseAdmin.from('business_leads').insert({business_id:businessId,customer_id:customerId,customer_name:customerName,customer_phone:customerPhone,customer_email:customerEmail,message,source:'business_profile',status:'new'}).select('id,business_id,customer_name,status,created_at').single();
    if(error)return res.status(400).json({error:error.message});
    await supabaseAdmin.from('business_analytics').insert({business_id:businessId,event_type:'enquiry',metadata:{lead_id:data.id,source:'business_profile'}}).then(()=>{});
    res.status(201).json({ok:true,lead:data,business:{id:business.id,name:business.name}});
  });
  app.get('/api/leads',requireUser,async(req,res)=>{
    const b=await ownedBusiness(req.user.id);if(!b)return res.status(404).json({error:'Business not found'});
    const {data,error}=await supabaseAdmin.from('business_leads').select('id,customer_name,customer_phone,customer_email,message,status,source,created_at,updated_at').eq('business_id',b.id).order('created_at',{ascending:false}).limit(100);
    if(error)return res.status(500).json({error:error.message});res.json({leads:data||[]});
  });
  app.patch('/api/leads/:id',requireUser,async(req,res)=>{
    const b=await ownedBusiness(req.user.id);if(!b)return res.status(404).json({error:'Business not found'});
    const status=String(req.body.status||'');if(!['new','contacted','qualified','closed','spam'].includes(status))return res.status(400).json({error:'Invalid lead status'});
    const {data,error}=await supabaseAdmin.from('business_leads').update({status,updated_at:new Date().toISOString()}).eq('id',req.params.id).eq('business_id',b.id).select('id,status,updated_at').single();
    if(error)return res.status(400).json({error:error.message});res.json({lead:data});
  });
  
app.post('/api/analytics/event',publicEventLimiter,async(req,res)=>{const id=String(req.body.business_id||'');const event=String(req.body.event_type||'').slice(0,40);if(!id||!event)return res.status(400).json({error:'business_id and event_type required'});const {data:business}=await supabaseAdmin.from('businesses').select('id').eq('id',id).eq('is_published',true).maybeSingle();if(!business)return res.status(404).json({error:'Business not found'});const allowed=['view','product_view','story_view','save','enquiry','call','whatsapp','offer_click'];if(!allowed.includes(event))return res.status(400).json({error:'Unsupported event'});const {error}=await supabaseAdmin.from('business_analytics').insert({business_id:id,event_type:event,metadata:req.body.metadata||{}});if(error)return res.status(400).json({error:error.message});res.json({ok:true})});
app.get('/api/analytics/owner',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!b)return res.status(404).json({error:'Business not found'});const {data,error}=await supabaseAdmin.from('business_analytics').select('event_type').eq('business_id',b.id);if(error)return res.status(500).json({error:error.message});const totals={views:0,enquiries:0,saves:0,product_views:0,story_views:0,call:0,whatsapp:0,offer_click:0};for(const x of data||[]){if(x.event_type==='view')totals.views++;if(x.event_type==='enquiry')totals.enquiries++;if(x.event_type==='save')totals.saves++;if(x.event_type==='product_view')totals.product_views++;if(x.event_type==='story_view')totals.story_views++;if(x.event_type==='call')totals.call++;if(x.event_type==='whatsapp')totals.whatsapp++;if(x.event_type==='offer_click')totals.offer_click++}res.json({business:b,totals})});

app.post('/api/funding/applications',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);if(!b)return res.status(400).json({error:'Create a business first'});const amount=Number(req.body.amount);const purpose=String(req.body.purpose||'').trim();const tenure=String(req.body.tenure||'');if(!Number.isFinite(amount)||amount<1000||amount>10000000||purpose.length<5)return res.status(400).json({error:'Enter a valid funding amount and purpose'});const {data,error}=await supabaseAdmin.from('funding_applications').insert({business_id:b.id,owner_id:req.user.id,amount,purpose:purpose.slice(0,2000),tenure:tenure.slice(0,40),status:'submitted'}).select('*').single();if(error)return res.status(400).json({error:error.message});res.status(201).json({application:data})});
app.get('/api/funding/applications',requireUser,async(req,res)=>{const b=await ownedBusiness(req.user.id);const {data,error}=await supabaseAdmin.from('funding_applications').select('*').eq('business_id',b?.id).order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json({applications:data||[]})});

app.post('/api/ai/chat',aiLimiter,async(req,res)=>{const message=String(req.body.message||'').trim().slice(0,4000);if(!message)return res.status(400).json({error:'Message required'});const context=String(req.body.context?.page||'home').replace(/[^a-z0-9_-]/gi,'').slice(0,40)||'home';const system=`You are Imphi, the friendly AI assistant inside Imphal Connect. Answer general questions clearly and helpfully. You can help with Imphal/Manipur travel, food, local businesses, events, shopping, business setup, and how to use this app. Never claim a booking, payment, subscription, upload, loan, or admin action happened unless an API confirms it. If the user asks for current/local facts that are not in your supplied context, say that live data may require a connected source rather than inventing facts. Current app page: ${context}. Keep responses concise but useful.`;
if(!process.env.AI_API_URL||!process.env.AI_API_KEY)return res.json({reply:`I’m Imphi ✨. I can help with your Imphal Connect journey, business setup, subscriptions, local discovery and planning. For fully general AI answers, add a secure AI_API_URL and AI_API_KEY to the server environment.

For now, tell me what you want to do and I’ll guide you through the app.`});
try{const body={model:process.env.AI_MODEL,messages:[{role:'system',content:system},{role:'user',content:message}],temperature:Math.min(1,Math.max(0,Number(process.env.AI_TEMPERATURE||1))),max_completion_tokens:Math.min(4000,Math.max(100,Number(process.env.AI_MAX_TOKENS||1000)))};const r=await fetch(process.env.AI_API_URL,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.AI_API_KEY}`},body:JSON.stringify(body),signal:AbortSignal.timeout(25000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||'AI provider error');const reply=String(d?.choices?.[0]?.message?.content||d?.output_text||'I could not generate a response right now.').trim();if(!reply)throw new Error('AI provider returned an empty response');res.json({reply:reply.slice(0,12000)})}catch(e){console.error('AI:',e.message);res.status(502).json({error:'AI service unavailable'})}});

// Admin APIs
app.get('/api/admin/overview',requireAdmin,async(_req,res)=>{const [b,p,f]=await Promise.all([supabaseAdmin.from('businesses').select('id,is_published,plan',{count:'exact',head:false}).limit(10000),supabaseAdmin.from('payment_events').select('id',{count:'exact',head:true}),supabaseAdmin.from('funding_applications').select('id',{count:'exact',head:true})]);const businesses=b.data||[];res.json({businesses:businesses.length,published:businesses.filter(x=>x.is_published).length,paid:businesses.filter(x=>['pro','elite'].includes(x.plan)).length,funding:f.count||0,payments:p.count||0})});
app.get('/api/admin/businesses',requireAdmin,async(_req,res)=>{const {data,error}=await supabaseAdmin.from('businesses').select('id,name,slug,category,is_verified,is_published,plan,subscription_status,created_at,owner_id').order('created_at',{ascending:false}).limit(500);if(error)return res.status(500).json({error:error.message});res.json({businesses:data||[]})});
app.patch('/api/admin/businesses/:id',requireAdmin,async(req,res)=>{const patch=Object.fromEntries(Object.entries(req.body||{}).filter(([k])=>['is_verified','is_published','plan','subscription_status'].includes(k)));patch.updated_at=new Date().toISOString();const {data,error}=await supabaseAdmin.from('businesses').update(patch).eq('id',req.params.id).select('*').single();if(error)return res.status(400).json({error:error.message});res.json({business:data})});
app.get('/api/admin/payments',requireAdmin,async(_req,res)=>{const {data,error}=await supabaseAdmin.from('payment_events').select('id,event_name,razorpay_id,created_at').order('created_at',{ascending:false}).limit(500);if(error)return res.status(500).json({error:error.message});res.json({events:data||[]})});
app.get('/api/admin/users',requireAdmin,async(_req,res)=>{const {data,error}=await supabaseAdmin.from('profiles').select('id,full_name,phone,role,created_at').order('created_at',{ascending:false}).limit(500);if(error)return res.status(500).json({error:error.message});const ids=(data||[]).map(x=>x.id);let users=[];if(ids.length){const {data:list}=await supabaseAdmin.auth.admin.listUsers({page:1,perPage:1000});users=(list?.users||[]).filter(u=>ids.includes(u.id)).map(u=>{const p=data.find(x=>x.id===u.id);return {...p,email:u.email}})}res.json({users})});
app.get('/api/admin/funding',requireAdmin,async(_req,res)=>{const {data,error}=await supabaseAdmin.from('funding_applications').select('*,businesses(name)').order('created_at',{ascending:false}).limit(500);if(error)return res.status(500).json({error:error.message});res.json({applications:(data||[]).map(x=>({...x,business:x.businesses}))})});
app.patch('/api/admin/funding/:id',requireAdmin,async(req,res)=>{const status=String(req.body.status||'');if(!['submitted','under_review','approved','rejected','disbursed','closed'].includes(status))return res.status(400).json({error:'Invalid funding status'});const {data,error}=await supabaseAdmin.from('funding_applications').update({status,reviewed_by:req.user.id,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',req.params.id).select('*').single();if(error)return res.status(400).json({error:error.message});res.json({application:data})});

app.get('/{*splat}',(req,res)=>res.sendFile(process.cwd()+'/public/index.html'));
app.listen(PORT,()=>console.log(`Imphal Connect v2 running on ${APP_URL}`));
