import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import compression from 'compression';
import rateLimit from 'express-rate-limit';
import QRCode from 'qrcode';
import {createClient} from '@supabase/supabase-js';
import {z} from 'zod';

const app=express(),port=Number(process.env.PORT||10000);
const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY,service=process.env.SUPABASE_SERVICE_ROLE_KEY;
const sb=service?createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}}):null;
const pub=key?createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}):null;
app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:'1mb'}));
app.use('/api',rateLimit({windowMs:900000,max:300,standardHeaders:true,legacyHeaders:false}));
const slugSchema=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).min(3).max(80);
async function user(req){const h=req.headers.authorization||'';if(!pub||!h.startsWith('Bearer '))return null;const {data,error}=await pub.auth.getUser(h.slice(7));return error?null:data.user}
async function auth(req,res,next){req.user=await user(req);if(!req.user)return res.status(401).json({error:'Authentication required'});next()}
async function owns(uid,id){const {data}=await sb.from('businesses').select('id').eq('id',id).eq('owner_id',uid).maybeSingle();return !!data}
const business=z.object({name:z.string().trim().min(2).max(120),description:z.string().max(1000).optional().default(''),phone:z.string().max(30).optional().default(''),whatsapp:z.string().max(30).optional().default(''),address:z.string().max(300).optional().default(''),city:z.string().max(100).optional().default(''),maps_url:z.string().url().max(500).optional().or(z.literal('')),logo_url:z.string().url().max(1000).optional().or(z.literal(''))});
const item=z.object({name:z.string().trim().min(1).max(120),description:z.string().max(500).optional().default(''),price:z.number().nonnegative().nullable().optional(),image_url:z.string().url().max(1000).optional().or(z.literal('')),type:z.enum(['product','service']).default('product'),is_active:z.boolean().default(true)});
app.get('/api/health',(_,r)=>r.json({ok:true,service:'localforge'}));
app.post('/api/auth/signup',async(req,res)=>{if(!pub)return res.status(503).json({error:'Supabase not configured'});const p=z.object({email:z.string().email(),password:z.string().min(8),name:z.string().min(2)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid signup data'});const {data,error}=await pub.auth.signUp({email:p.data.email,password:p.data.password,options:{data:{name:p.data.name}}});if(error)return res.status(400).json({error:error.message});res.status(201).json(data)});
app.post('/api/auth/login',async(req,res)=>{if(!pub)return res.status(503).json({error:'Supabase not configured'});const p=z.object({email:z.string().email(),password:z.string().min(8)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid login data'});const {data,error}=await pub.auth.signInWithPassword(p.data);if(error)return res.status(401).json({error:error.message});res.json(data)});
app.get('/api/me',auth,async(req,res)=>{const [{data:profile},{data:businesses}]=await Promise.all([sb.from('profiles').select('*').eq('id',req.user.id).maybeSingle(),sb.from('businesses').select('*').eq('owner_id',req.user.id).order('created_at',{ascending:false})]);res.json({user:req.user,profile,businesses:businesses||[]})});
app.post('/api/businesses',auth,async(req,res)=>{const p=business.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid business data'});let slug=p.data.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'business';const base=slug;for(let i=2;;i++){const {data}=await sb.from('businesses').select('id').eq('slug',slug).maybeSingle();if(!data)break;slug=base+'-'+i}const {data,error}=await sb.from('businesses').insert({...p.data,slug,owner_id:req.user.id}).select('*').single();if(error)return res.status(400).json({error:error.message});res.status(201).json(data)});
app.patch('/api/businesses/:id',auth,async(req,res)=>{if(!await owns(req.user.id,req.params.id))return res.status(403).json({error:'Forbidden'});const p=business.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid data'});const {data,error}=await sb.from('businesses').update(p.data).eq('id',req.params.id).select('*').single();if(error)return res.status(400).json({error:error.message});res.json(data)});
app.get('/api/businesses/:id/items',auth,async(req,res)=>{if(!await owns(req.user.id,req.params.id))return res.status(403).json({error:'Forbidden'});const {data,error}=await sb.from('items').select('*').eq('business_id',req.params.id).order('sort_order').order('created_at');if(error)return res.status(400).json({error:error.message});res.json(data||[])});
app.post('/api/businesses/:id/items',auth,async(req,res)=>{if(!await owns(req.user.id,req.params.id))return res.status(403).json({error:'Forbidden'});const p=item.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid item'});const {data,error}=await sb.from('items').insert({...p.data,business_id:req.params.id}).select('*').single();if(error)return res.status(400).json({error:error.message});res.status(201).json(data)});
app.delete('/api/items/:id',auth,async(req,res)=>{const {data:i}=await sb.from('items').select('business_id').eq('id',req.params.id).maybeSingle();if(!i||!await owns(req.user.id,i.business_id))return res.status(403).json({error:'Forbidden'});const {error}=await sb.from('items').delete().eq('id',req.params.id);if(error)return res.status(400).json({error:error.message});res.status(204).end()});
app.get('/api/public/business/:slug',async(req,res)=>{if(!slugSchema.safeParse(req.params.slug).success)return res.status(404).json({error:'Not found'});const {data:b,error}=await sb.from('businesses').select('id,name,slug,logo_url,description,phone,whatsapp,address,city,maps_url,opening_hours').eq('slug',req.params.slug).eq('is_published',true).eq('is_suspended',false).maybeSingle();if(error||!b)return res.status(404).json({error:'Business not found'});const {data:items}=await sb.from('items').select('id,name,description,price,image_url,type').eq('business_id',b.id).eq('is_active',true).order('sort_order');res.json({...b,items:items||[]})});
app.post('/api/leads/:businessId',async(req,res)=>{const p=z.object({name:z.string().min(2).max(100),phone:z.string().min(5).max(30),email:z.string().email().max(200).optional().or(z.literal('')),message:z.string().max(1000).optional().default('')}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid contact details'});const {data:b}=await sb.from('businesses').select('id').eq('id',req.params.businessId).eq('is_published',true).eq('is_suspended',false).maybeSingle();if(!b)return res.status(404).json({error:'Business unavailable'});const {error}=await sb.from('leads').insert({...p.data,business_id:b.id,source:'public'});if(error)return res.status(400).json({error:error.message});res.status(201).json({ok:true})});
app.post('/api/events/:businessId',async(req,res)=>{if(!['view','whatsapp_click','call_click','map_click','share','qr_scan'].includes(req.body?.event_type))return res.status(400).end();await sb.from('analytics_events').insert({business_id:req.params.businessId,event_type:req.body.event_type,metadata:req.body.metadata||{}});res.status(204).end()});
app.get('/api/public/business/:slug/qr.svg',async(req,res)=>{const {data:b}=await sb.from('businesses').select('slug').eq('slug',req.params.slug).eq('is_published',true).eq('is_suspended',false).maybeSingle();if(!b)return res.status(404).end();const base=process.env.APP_URL||'http://localhost:'+port;res.type('image/svg+xml').send(await QRCode.toString(base.replace(/\/$/,'')+'/b/'+b.slug,{type:'svg',margin:1,width:512}))});
app.use(express.static(process.cwd()+'/localforge/public'));
app.get('/b/:slug',(req,res)=>res.sendFile(process.cwd()+'/localforge/public/business.html'));
app.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Route not found'});res.sendFile(process.cwd()+'/localforge/public/index.html')});
app.listen(port,()=>console.log('LocalForge on '+port));
